#Database:
MYSQL_USERNAME: root
MYSQL_PASSWORD: ${STACKHERO_MYSQL_ROOT_PASSWORD}
MYSQL_HOST: ${STACKHERO_MYSQL_HOST}
MYSQL_PORT: 3306
MYSQL_DATABASE: invoiceapp

#Server config:
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

#Email config:
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: dizvabole@gmail.com
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://${STACKHERO_MYSQL_HOST}:${CONTAINER_PORT}

UI_APP_URL: http://${STACKHERO_MYSQL_HOST}:4200

JWT_SECRET: mysupercomplexsecret

